### ISSUE TITLE
Sync source code?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [libretro-mirrors/libretro-ppsspp#71]
I saw that your fork is really old. How much difficult would it be to sync up and re-build the core?

Thanks in advance

**Comment by fr500** [comment]
Very difficult

**Comment by julianxhokaxhiu** [comment]
Did you try to talk with the developer? Is it possible maybe to ask him to re-organize his code to make it more modular and so, libretro friendly?

**Comment by hrydgard** [comment]
I don't know what's difficult about it. If retroarch needs some specific changes to make things easier, tell us or make a pull request.

**Comment by unknownbrackets** [comment]
Things like this just scare me:

https://github.com/libretro/libretro-ppsspp/blob/master/Common/CPUDetect.cpp#L42

What is it that requires significant changes?  It seems like the real problem there was just a missing header.

-[Unknown]

**Comment by twinaphex** [comment]
You might be right that certain of our teammembers like leiradel might have went a bit overzealous during the conversion where we tried to make it work with Mingw.

I think at this point the best thing we could do is start the port from scratch from your latest sources and then work with you on coming up with decent solutions that won't clash completely with upstream. 

I'll probably be able to commit myself to this beginning next week. I think both projects can stand to benefit quite a bit from this, upstream in this case getting better compatibility with Mingw and in our case a core that can be better maintained and is more in lock-step with upstream.

**Comment by fr500** [comment]
@hrydgard the biggest complication is merging the MSVC solution since merging MSVC project files
The only viable alternative I see would be to have a libretro configuraton in the project. Or to make a static makefile for mingw/libretro but our experience with the mingw build was that it was about 60% slower with the same optimization level. Maybe the jit wasn't working correctly or something.

I agree the fork has diverged too much so it's probably better to just start over.

**Comment by unknownbrackets** [comment]
Can you use the same CMake we use for Linux/iOS/etc.?

My experience with the Linux port is that performance is not really significantly worse, so I imagine mingw wouldn't be either.  However, if you were disabling SSE by nulling out all the CPU feature bits, that could definitely sacrifice a lot of optimizations we have.  Maybe that was the reason for the poor performance.

-[Unknown]

**Comment by fr500** [comment]
I guess we could yes. I used to build mgba with CMake on windows for a while. That would be easier than having a separate configuration on the MSVC project right?

**Comment by twinaphex** [comment]
I am generally a proponent of static Makefiles. I might maintain the static Makefile ones myself if you really don't want them, but I generally don't want to deal with CMake and it being a dependency in general. For libretro-super build purposes I want zero dependencies other than just the basic toolchain.

However, for the upstream code that would be committed, we could push it without the static Makefile. It would just be something I would maintain myself in the shallow fork as the only change.

**Comment by unknownbrackets** [comment]
You can probably start from our Android makefiles then, although they have some NDKisms in them.  For the most part, things we add there would need to be added to libretro.

-[Unknown]

**Comment by julianxhokaxhiu** [comment]
Wow, I didn't expect so many feedbacks!

Regarding my side I could test it for you once you'll have a "beta" status-quo of your code. But meanwhile I can just say thank you very much for all the effort you'll put into this.

**Comment by dankcushions** [comment]
Related: https://github.com/hrydgard/ppsspp/pull/8778

**Comment by orbea** [comment]
Here is a started attempt to merge upstream ppsspp.

https://github.com/libretro/libretro-ppsspp/pull/84

**Comment by julianxhokaxhiu** [comment]
I saw that now on retroarch a lot of new core are ramping up. This means that *hopefully* we will see PPSSPP joining the round, am I right?

**Comment by raetiacorvus** [comment]
According to latest [news](https://www.libretro.com/index.php/retroarch-1-6-4-released/): "Priority number one absolutely right now is PPPSSPP and Supermodel. We are going to get that into your hands ASAP as promised."

I hope the team follows up on the idea of upstreaming as much as possible.

**Comment by julianxhokaxhiu** [comment]
It has been fixed by the awesome effort by @twinaphex and @hrydgard working together,

Awesome job guys and thank you again for this :) Cheers!
